### PR TITLE
Algorithm1 testcases

### PR DESCRIPTION
**Pull request by ProjectZuki**
Created test cases for Bayesian Model and Max Posterior

### CODE REVIEW

**Review by Dorffasaurus — CHANGES_REQUESTED** [review]
Can you remove the binary .DS_Store files from WordCountAlgo and Bayes folders?

**Comment by ProjectZuki** [comment]
Removed Bayes/.DS_Store and WordCountAlgo/.DS_Store

**Review by Dorffasaurus — CHANGES_REQUESTED** [review]
DS_Store is in root folder as well. Can you remove that?

**Review by Dorffasaurus — APPROVED** [review]
Looks good.

**Pull request merged**
